import { neon } from "@neondatabase/serverless";
import { artists, articles, events, magazine, radarProjects, releases, type Artist, type Article, type Event, type MagazineStory, type RadarProject, type Release } from "@/lib/ia-content";

export type CmsRecord = { id?: string; sourceId?: string; sourceUrl?: string; slug: string; path?: string; title?: string; name?: string; subtitle?: string; excerpt?: string; body?: string; bodyHtml?: string; metaTitle?: string; metaDescription?: string; canonicalUrl?: string; status?: "draft" | "published" | "archived"; imageUrl?: string; featuredImage?: string; publishedAt?: string; date?: string; author?: string; editorialType?: "article" | "interview" | "spotlight" | "magazine"; categories?: string[]; tags?: string[]; migrationWarnings?: string[]; [key: string]: unknown };
export type CmsPage = CmsRecord & { path: string; title: string };
export type ContentCollections = { artists: Artist[]; releases: Release[]; articles: Article[]; magazine: MagazineStory[]; radarProjects: RadarProject[]; events: Event[]; pages: CmsPage[]; categories: CmsRecord[]; archives: CmsRecord[] };
const MAX_CONTENT_BYTES = 20 * 1024 * 1024;
const seedContent: ContentCollections = { artists, releases, articles, magazine, radarProjects, events, pages: [], categories: [], archives: [] };

export function hasContentDatabase() { return Boolean(process.env.DATABASE_URL); }
function sql() { if (!process.env.DATABASE_URL) throw new Error("DATABASE_URL is not configured"); return neon(process.env.DATABASE_URL); }
function cleanString(value: unknown, fallback = "", max = 5000) { return typeof value === "string" ? value.trim().slice(0, max) : fallback; }
function cleanArray(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim().slice(0, 300)).filter(Boolean).slice(0, 100) : []; }
function cleanRecords(value: unknown) { return Array.isArray(value) ? value.filter((item) => item && typeof item === "object" && !Array.isArray(item)).slice(0, 10000).map(cleanRecord) : []; }
function cleanRelated(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return {}; return Object.fromEntries(Object.entries(value).map(([key, items]) => [key, cleanArray(items)])); }
function cleanRecord(value: unknown) { if (!value || typeof value !== "object" || Array.isArray(value)) return { slug: "" }; const record = value as Record<string, unknown>; const status = record.status === "draft" || record.status === "archived" ? record.status : "published"; return { ...record, id: cleanString(record.id, "", 120), sourceId: cleanString(record.sourceId, "", 120), sourceUrl: cleanString(record.sourceUrl, "", 2000), slug: cleanString(record.slug, "", 300), path: cleanString(record.path, "", 500), title: cleanString(record.title), name: cleanString(record.name), project: cleanString(record.project), artist: cleanString(record.artist), bio: cleanString(record.bio), subtitle: cleanString(record.subtitle), excerpt: cleanString(record.excerpt), body: cleanString(record.body, "", 2000000), bodyHtml: cleanString(record.bodyHtml, "", 2000000), brief: cleanString(record.brief), category: cleanString(record.category), date: cleanString(record.date, "", 100), publishedAt: cleanString(record.publishedAt, "", 100), author: cleanString(record.author), metaTitle: cleanString(record.metaTitle, "", 300), metaDescription: cleanString(record.metaDescription, "", 1000), canonicalUrl: cleanString(record.canonicalUrl, "", 2000), year: cleanString(record.year), location: cleanString(record.location), imageQuery: cleanString(record.imageQuery), imageUrl: cleanString(record.imageUrl, "", 2000), featuredImage: cleanString(record.featuredImage, "", 2000), status, tags: cleanArray(record.tags), categories: cleanArray(record.categories), migrationWarnings: cleanArray(record.migrationWarnings), related: cleanRelated(record.related) }; }
export function normalizeContent(input: unknown): ContentCollections { const value = input && typeof input === "object" ? input as Partial<ContentCollections> : {}; return { artists: cleanRecords(value.artists) as Artist[], releases: cleanRecords(value.releases) as Release[], articles: cleanRecords(value.articles) as Article[], magazine: cleanRecords(value.magazine) as MagazineStory[], radarProjects: cleanRecords(value.radarProjects) as RadarProject[], events: cleanRecords(value.events) as Event[], pages: cleanRecords(value.pages) as CmsPage[], categories: cleanRecords(value.categories) as CmsRecord[], archives: cleanRecords(value.archives) as CmsRecord[] }; }

export async function ensureContentTable() { await sql()`CREATE TABLE IF NOT EXISTS studio_content (id integer PRIMARY KEY, content jsonb NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`; }
export async function readContent(): Promise<ContentCollections> { if (!hasContentDatabase()) return seedContent; await ensureContentTable(); const rows = await sql()`SELECT content FROM studio_content WHERE id = 1 LIMIT 1` as { content: unknown }[]; return rows[0]?.content ? normalizeContent(rows[0].content) : seedContent; }
export async function readPublishedContent(): Promise<ContentCollections> { const content = await readContent(); function published<T>(items: T[]): T[] { return items.filter((item) => { const status = item && typeof item === "object" && "status" in item ? (item as { status?: string }).status : undefined; return status !== "draft" && status !== "archived"; }); } return { ...content, artists: published(content.artists), releases: published(content.releases), articles: published(content.articles), magazine: published(content.magazine), radarProjects: published(content.radarProjects), events: published(content.events), pages: published(content.pages), categories: published(content.categories), archives: published(content.archives) }; }
export async function writeContent(input: unknown) { const content = normalizeContent(input); if (Buffer.byteLength(JSON.stringify(content), "utf8") > MAX_CONTENT_BYTES) throw new Error("CMS content payload is too large"); await ensureContentTable(); await sql()`INSERT INTO studio_content (id, content, updated_at) VALUES (1, ${JSON.stringify(content)}::jsonb, now()) ON CONFLICT (id) DO UPDATE SET content = EXCLUDED.content, updated_at = now()`; return content; }
