"use client";

import { useState } from "react";
import { heroConfig, homepageContent } from "@/lib/radar-content";

const STORAGE_KEY = "radarcharts-content-overrides";
type Overrides = { heroHeadline: string; subheadline: string; ticker: string; ctaEmail: string };
const defaults: Overrides = { heroHeadline: heroConfig.headline.join("\n"), subheadline: heroConfig.subheadline, ticker: homepageContent.ticker.join(", "), ctaEmail: homepageContent.cta.email };
function initialValues(): Overrides { if (typeof window === "undefined") return defaults; try { const stored = window.localStorage.getItem(STORAGE_KEY); return stored ? { ...defaults, ...JSON.parse(stored) } : defaults; } catch { return defaults; } }

export function RadarAdminPanel() {
  const [values, setValues] = useState<Overrides>(initialValues);
  const [saved, setSaved] = useState(false);
  function update(key: keyof Overrides, value: string) { setValues((current) => ({ ...current, [key]: value })); setSaved(false); }
  function save() { window.localStorage.setItem(STORAGE_KEY, JSON.stringify(values)); setSaved(true); }
  function reset() { window.localStorage.removeItem(STORAGE_KEY); setValues(defaults); setSaved(true); }
  return <main className="min-h-screen bg-paper px-4 pb-20 pt-24 text-ink md:px-8"><div className="mx-auto max-w-6xl"><div className="flex flex-wrap items-end justify-between gap-6 border-b-2 border-ink pb-8"><div><p className="font-mono text-xs font-bold uppercase tracking-widest">(Studio / Admin)</p><h1 className="mt-4 display text-[clamp(3rem,9vw,8rem)] leading-[.86]">RADAR<br /><span className="text-flare">Control.</span></h1></div><p className="max-w-xs font-mono text-xs uppercase leading-relaxed tracking-widest text-muted-foreground">Edit the signal that appears on the public homepage. Changes are saved in this browser for preview and handoff.</p></div><div className="mt-10 grid gap-8 md:grid-cols-2"><label className="font-mono text-xs font-bold uppercase tracking-widest">Hero headline<textarea value={values.heroHeadline} onChange={(e) => update("heroHeadline", e.target.value)} className="mt-3 min-h-32 w-full brut-border bg-transparent p-4 font-display text-3xl font-extrabold uppercase outline-none focus:ring-2 focus:ring-flare" /></label><label className="font-mono text-xs font-bold uppercase tracking-widest">Hero subheadline<textarea value={values.subheadline} onChange={(e) => update("subheadline", e.target.value)} className="mt-3 min-h-32 w-full brut-border bg-transparent p-4 font-mono text-sm uppercase outline-none focus:ring-2 focus:ring-flare" /></label><label className="font-mono text-xs font-bold uppercase tracking-widest">Ticker items<textarea value={values.ticker} onChange={(e) => update("ticker", e.target.value)} className="mt-3 min-h-32 w-full brut-border bg-transparent p-4 font-mono text-sm uppercase outline-none focus:ring-2 focus:ring-flare" /></label><label className="font-mono text-xs font-bold uppercase tracking-widest">Contact email<input value={values.ctaEmail} onChange={(e) => update("ctaEmail", e.target.value)} className="mt-3 w-full brut-border bg-transparent p-4 font-mono text-sm outline-none focus:ring-2 focus:ring-flare" /></label></div><div className="mt-10 flex flex-wrap gap-4"><button onClick={save} className="brut-border bg-flare px-6 py-4 font-mono text-xs font-bold uppercase tracking-widest text-flare-foreground">{saved ? "Saved" : "Save changes"}</button><button onClick={reset} className="brut-border px-6 py-4 font-mono text-xs font-bold uppercase tracking-widest">Reset seed content</button></div><p className="mt-8 max-w-2xl font-mono text-xs uppercase leading-relaxed tracking-widest text-muted-foreground">Content is schema-first in <code>src/lib/radar-content.ts</code>. This starter admin layer uses local browser persistence until a CMS or database connector is selected, avoiding a disruptive rebuild of the existing site architecture.</p></div></main>;
}
