"use client";

import { useState } from "react";
import { caseStudies } from "@/lib/case-studies";
import { defaultSiteOverrides, SITE_OVERRIDES_KEY, type SiteOverrides } from "@/lib/site-overrides";
import { heroConfig } from "@/lib/radar-content";

const initial: SiteOverrides = { ...defaultSiteOverrides, logoText: "remRADAR", featuredSlugs: caseStudies.map((study) => study.slug), heroHeadline: heroConfig.headline, heroSubheadline: heroConfig.subheadline, tickerItems: ["Artist Spotlight", "Releases", "RADARArticles", "On The Radar", "Campaigns"] };
function load(): SiteOverrides { if (typeof window === "undefined") return initial; try { const raw = window.localStorage.getItem(SITE_OVERRIDES_KEY); return raw ? { ...initial, ...JSON.parse(raw) } : initial; } catch { return initial; } }

const fieldClass = "mt-2 w-full brut-border bg-transparent p-3 font-mono text-sm outline-none focus:ring-2 focus:ring-flare";
const labelClass = "font-mono text-[11px] font-bold uppercase tracking-widest";

export function RadarAdminPanel() {
  const [values, setValues] = useState<SiteOverrides>(load);
  const [saved, setSaved] = useState(false);
  const [newKey, setNewKey] = useState("hero:studio-signal");
  const [newUrl, setNewUrl] = useState("");
  const update = <K extends keyof SiteOverrides>(key: K, value: SiteOverrides[K]) => { setValues((current) => ({ ...current, [key]: value })); setSaved(false); };
  const save = () => { window.localStorage.setItem(SITE_OVERRIDES_KEY, JSON.stringify(values)); window.dispatchEvent(new Event("radar-overrides-updated")); setSaved(true); };
  const reset = () => { window.localStorage.removeItem(SITE_OVERRIDES_KEY); setValues(initial); window.dispatchEvent(new Event("radar-overrides-updated")); setSaved(true); };
  const toggleFeatured = (slug: string) => update("featuredSlugs", values.featuredSlugs.includes(slug) ? values.featuredSlugs.filter((item) => item !== slug) : [...values.featuredSlugs, slug]);
  const addAsset = () => { if (!newKey.trim() || !newUrl.trim()) return; update("media", { ...values.media, [newKey.trim()]: newUrl.trim() }); setNewUrl(""); };
  const removeAsset = (key: string) => { const next = { ...values.media }; delete next[key]; update("media", next); };

  return <main className="min-h-screen bg-paper px-4 pb-24 pt-24 text-ink md:px-8"><div className="mx-auto max-w-7xl"><header className="flex flex-wrap items-end justify-between gap-8 border-b-2 border-ink pb-8"><div><p className={labelClass}>(Studio / Admin / Site editor)</p><h1 className="mt-4 display text-[clamp(3rem,9vw,8rem)] leading-[.86]">RADAR<br /><span className="text-flare">Control.</span></h1></div><p className="max-w-sm font-mono text-xs uppercase leading-relaxed tracking-widest text-muted-foreground">A WordPress-style control room for the live site: replace media, update tags and icons, select featured projects, and manage SEO without touching the composition.</p></header>

<section className="mt-10"><div className="flex items-center justify-between border-b-2 border-ink pb-3"><h2 className="display text-3xl">Media library</h2><span className={labelClass}>{Object.keys(values.media).length} managed assets</span></div><div className="mt-5 grid gap-4 md:grid-cols-[1fr_2fr_auto]"><select value={newKey} onChange={(e) => setNewKey(e.target.value)} className={fieldClass}><option value="hero:studio-signal">Hero / Studio Signal</option><option value="hero:night-drive">Hero / Night Drive</option><option value="hero:press-room">Hero / Press Room</option>{caseStudies.map((study) => <option key={study.slug} value={`work:${study.slug}`}>Work / {study.client}</option>)}</select><input value={newUrl} onChange={(e) => setNewUrl(e.target.value)} placeholder="Paste an image/video URL or uploaded asset URL" className={fieldClass} /><button onClick={addAsset} className="brut-border bg-flare px-5 py-3 font-mono text-xs font-bold uppercase tracking-widest text-flare-foreground">Add asset</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{Object.entries(values.media).map(([key, url]) => <div key={key} className="flex items-center gap-3 brut-border p-3"><div className="h-16 w-24 shrink-0 bg-ink bg-cover bg-center" style={{ backgroundImage: `url(${url})` }} /><div className="min-w-0 flex-1"><p className={labelClass}>{key}</p><p className="mt-1 truncate font-mono text-xs text-muted-foreground">{url}</p></div><button onClick={() => removeAsset(key)} className="font-mono text-xs font-bold uppercase tracking-widest text-flare">Remove</button></div>)}</div></section>

<section className="mt-14 grid gap-10 lg:grid-cols-2"><div><h2 className="display border-b-2 border-ink pb-3 text-3xl">Site tags</h2><div className="mt-5 grid gap-5"><label className={labelClass}>Logo / wordmark<input value={values.logoText} onChange={(e) => update("logoText", e.target.value)} className={fieldClass} /></label><label className={labelClass}>Ticker icon or SVG symbol<input value={values.tickerIcon} onChange={(e) => update("tickerIcon", e.target.value)} className={fieldClass} /></label><label className={labelClass}>Ticker items<textarea value={values.tickerItems.join(", ")} onChange={(e) => update("tickerItems", e.target.value.split(",").map((item) => item.trim()).filter(Boolean))} className={`${fieldClass} min-h-24`} /></label></div></div><div><h2 className="display border-b-2 border-ink pb-3 text-3xl">Hero content</h2><div className="mt-5 grid gap-5"><label className={labelClass}>Headline<textarea value={values.heroHeadline.join("\n")} onChange={(e) => update("heroHeadline", e.target.value.split("\n"))} className={`${fieldClass} min-h-28 font-display text-2xl font-extrabold uppercase`} /></label><label className={labelClass}>Subheadline<textarea value={values.heroSubheadline} onChange={(e) => update("heroSubheadline", e.target.value)} className={`${fieldClass} min-h-24`} /></label></div></div></section>

<section className="mt-14"><h2 className="display border-b-2 border-ink pb-3 text-3xl">Featured content</h2><div className="mt-5 grid gap-3 md:grid-cols-3">{caseStudies.map((study) => <button key={study.slug} onClick={() => toggleFeatured(study.slug)} className={`brut-border p-4 text-left transition-colors ${values.featuredSlugs.includes(study.slug) ? "bg-flare text-flare-foreground" : ""}`}><span className={labelClass}>{values.featuredSlugs.includes(study.slug) ? "Featured" : "Hidden"}</span><strong className="mt-3 block display text-2xl">{study.client}</strong><span className="mt-2 block font-mono text-xs uppercase">{study.title}</span></button>)}</div></section>

<section className="mt-14"><h2 className="display border-b-2 border-ink pb-3 text-3xl">SEO & social</h2><div className="mt-5 grid gap-5 md:grid-cols-2"><label className={labelClass}>Meta title<input value={values.seoTitle} onChange={(e) => update("seoTitle", e.target.value)} className={fieldClass} /></label><label className={labelClass}>Social image URL<input value={values.socialImage} onChange={(e) => update("socialImage", e.target.value)} className={fieldClass} /></label><label className={`${labelClass} md:col-span-2`}>Meta description<textarea value={values.seoDescription} onChange={(e) => update("seoDescription", e.target.value)} className={`${fieldClass} min-h-24`} /></label></div></section>

<div className="sticky bottom-4 mt-12 flex flex-wrap items-center gap-4 border-2 border-ink bg-paper p-4"><button onClick={save} className="brut-border bg-flare px-6 py-4 font-mono text-xs font-bold uppercase tracking-widest text-flare-foreground">{saved ? "Published to this browser" : "Save / publish changes"}</button><button onClick={reset} className="brut-border px-6 py-4 font-mono text-xs font-bold uppercase tracking-widest">Reset all overrides</button><span className="font-mono text-xs uppercase tracking-widest text-muted-foreground">{saved ? "Public components update immediately in this browser." : "Unsaved changes"}</span></div><p className="mt-8 max-w-3xl font-mono text-xs uppercase leading-relaxed tracking-widest text-muted-foreground">This is the CMS UI layer. It supports media URLs and uploaded storage paths today. To make edits shared across editors and devices, connect this same schema to WordPress, Sanity, Payload, or a database-backed API; the public components already consume the centralized override shape.</p></div></main>;
}
