"use client";
import type { SelectedWorkItem } from "@/types/site-config";

const input = "w-full rounded border border-neutral-800 bg-neutral-950 px-3 py-2 text-xs text-neutral-200 outline-none focus:border-white";
type ProjectTicker = { enabled: boolean; speedSeconds: number; label: string; projectSlugs: string[] };
export function ProjectSelectorTickerEditor({ value, projects, onChange }: { value: ProjectTicker; projects: SelectedWorkItem[]; onChange: (value: ProjectTicker) => void }) {
  const toggle = (slug: string) => onChange({ ...value, projectSlugs: value.projectSlugs.includes(slug) ? value.projectSlugs.filter((item) => item !== slug) : [...value.projectSlugs, slug] });
  return <section className="space-y-4 rounded-xl border border-neutral-800 bg-neutral-900 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-neutral-500">Ticker 3 / Project selector</p><h2 className="mt-1 text-lg font-bold uppercase">Select project scrolling</h2><p className="mt-2 max-w-xl font-mono text-[10px] uppercase leading-relaxed tracking-widest text-neutral-500">Choose which selected-work projects appear in the second scrolling marquee.</p></div><label className="flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest text-neutral-400"><input type="checkbox" checked={value.enabled} onChange={(e) => onChange({ ...value, enabled: e.target.checked })} /> Enabled</label></div><div className="grid gap-3 sm:grid-cols-[1fr_10rem]"><label className="text-[10px] uppercase tracking-widest text-neutral-500">Scrolling label<input className={input} value={value.label} onChange={(e) => onChange({ ...value, label: e.target.value })} /></label><label className="text-[10px] uppercase tracking-widest text-neutral-500">Speed (seconds)<input className={input} type="number" min={8} max={120} value={value.speedSeconds} onChange={(e) => onChange({ ...value, speedSeconds: Number(e.target.value) || 30 })} /></label></div><div className="grid gap-2 md:grid-cols-3">{projects.map((project) => <label key={project.id} className="flex cursor-pointer items-center gap-3 rounded border border-neutral-800 bg-black p-3 font-mono text-[10px] uppercase tracking-widest text-neutral-300"><input type="checkbox" checked={value.projectSlugs.includes(project.caseStudyUrl.split("/").pop() || project.id)} onChange={() => toggle(project.caseStudyUrl.split("/").pop() || project.id)} /><span><b className="text-neutral-500">{project.number}</b> {project.artistOrProjectName}</span></label>)}</div></section>;
}
