import type { Metadata } from "next";
import { IaIndex } from "@/components/marketing/IaPages";
import { readPublishedContent } from "@/lib/content-server";
import { publicSiteUrl, readPublicSiteOverrides, safeSocialImageUrl } from "@/lib/public-site";
import { StructuredData } from "@/components/StructuredData";
import { breadcrumbStructuredData, collectionPageStructuredData } from "@/lib/seo-schema";
export const revalidate = 3600;
export async function generateMetadata(): Promise<Metadata> { const settings = await readPublicSiteOverrides(); const title = "Magazine"; const description = "Long-form interviews, special episodes, and cultural stories from the RADARCharts editorial archive."; const image = safeSocialImageUrl(settings.socialImage); return { title, description, alternates: { canonical: "/ontheradar/magazine" }, openGraph: { type: "website", url: `${publicSiteUrl()}/ontheradar/magazine`, siteName: settings.siteName, title, description, images: [{ url: image, alt: title }] }, twitter: { card: "summary_large_image", site: settings.xHandle, title, description, images: [image] } }; }
export default async function MagazinePage() { const { magazine } = await readPublishedContent(); const description = "Long-form interviews, special episodes, and cultural stories from the RADARCharts editorial archive."; return <><StructuredData data={collectionPageStructuredData({ name: "Magazine", description, canonicalUrl: "/ontheradar/magazine", about: "Magazine" })} /><StructuredData data={breadcrumbStructuredData([{ name: "RADARCharts", url: "/" }, { name: "On The Radar", url: "/ontheradar" }, { name: "Magazine", url: "/ontheradar/magazine" }])} /><IaIndex eyebrow="(On The Radar / Magazine)" title="Magazine" intro="Long-form interviews, conversations, and cultural stories with room to breathe." items={magazine} basePath="/ontheradar/magazine" /></>; }
