import Link from "next/link";
import { IaIndex } from "@/components/marketing/IaPages";
import { readPublishedContent } from "@/lib/content-server";
import { recordsForMagazineSubtype } from "@/lib/editorial-archives";
export const revalidate = 3600;
export default async function MagazinePage() {
  const { articles, magazine } = await readPublishedContent();
  const specialEpisodes = recordsForMagazineSubtype(articles, "Special Episode");
  const magazineEpisodes = recordsForMagazineSubtype(articles, "Magazine Episode");
  return <div><section className="border-b-2 border-ink px-4 pb-10 pt-24 md:px-8"><p className="font-mono text-xs font-bold uppercase tracking-widest text-muted-foreground">(On The Radar / Magazine)</p><h1 className="mt-4 display text-[clamp(3rem,11vw,11rem)] leading-[.84]">Magazine<span className="text-flare">.</span></h1><p className="mt-8 max-w-2xl font-mono text-sm uppercase leading-relaxed tracking-wide text-muted-foreground">A separate editorial lane for Special Episodes and Magazine Episodes. Magazine entries retain one canonical article identity and do not appear in Press or Spotlight.</p><div className="mt-8 flex flex-wrap gap-4 font-mono text-xs font-bold uppercase tracking-widest"><Link className="text-flare hover:underline" href="#special-episodes">Special Episodes ({specialEpisodes.length})</Link><Link className="text-flare hover:underline" href="#magazine-episodes">Magazine Episodes ({magazineEpisodes.length})</Link></div></section>{magazine.length > 0 && <IaIndex eyebrow="(Magazine / Featured)" title="Featured" intro="Legacy standalone Magazine content remains discoverable here while its subtype metadata is reviewed; no new public subtype is invented." items={magazine} basePath="/ontheradar/magazine" />}<section id="special-episodes"><IaIndex eyebrow="(Magazine / Special Episode)" title="Special Episodes" intro="Long-form special guest episodes from the canonical Magazine taxonomy." items={specialEpisodes} basePath="/ontheradar/articles" /></section><section id="magazine-episodes"><IaIndex eyebrow="(Magazine / Magazine Episode)" title="Magazine Episodes" intro="The regular Magazine Episode lane, separate from Press and Spotlight." items={magazineEpisodes} basePath="/ontheradar/articles" /></section></div>;
}
